added basic file for response tests.
celenium-io/celestia-indexer pull request #147
Opened 2024-03-08 06:38 UTC by vvuwei

2024-03-08 12:04 UTC, aopoltorzhicky requested changes
Пусто

2024-03-08 18:18 UTC, A1exCoon approved these changes

2024-03-09 20:02 UTC, dmirgaleev approved these changes

2024-03-10 13:37 UTC, aopoltorzhicky requested changes

2024-03-10 13:37 UTC, aopoltorzhicky commented on cmd/api/cache/response_test.go
> +	_ "bytes"
Это зачем?

2024-03-10 15:37 UTC, aopoltorzhicky approved these changes

2024-03-10 17:08 UTC, merged