Feat/rollup grouped stats
celenium-io/celestia-indexer pull request #306
Opened 2024-11-14 12:26 UTC by k-karuna

2024-11-14 12:34 UTC, aopoltorzhicky requested changes

2024-11-14 12:34 UTC, aopoltorzhicky commented on cmd/api/handler/rollup_test.go
> +			testRollupWithGroupedStats = storage.RollupGroupedStats{
Ты в начале файла вроде создал этот объект. Либо там, либо здесь оставить надо

2024-11-14 12:34 UTC, aopoltorzhicky commented on internal/storage/postgres/rollup.go
> +	err = r.DB().NewSelect().
Я бы сделал валидацию дополнительную на func, чтобы было надежно. Через switch/case запрос написал бы в зависимости от func. Плюсовать параметры в sql запрос -- плохая практика

2024-11-14 12:34 UTC, aopoltorzhicky commented on internal/storage/rollup.go
> +	Func   string
Тест на запрос в Бд)

И здесь теги 'bun', наверное, нужны

2024-11-14 13:19 UTC, k-karuna commented on internal/storage/rollup.go
> +	Func   string
Ты про какие теги bun? В `RollupGroupStatsFilters ` их нет вроде бы..

2024-11-14 13:20 UTC, aopoltorzhicky commented on internal/storage/rollup.go
> +	Func   string
А, да. Это ж фильтры😁

2024-11-15 14:22 UTC, aopoltorzhicky approved these changes

2024-11-15 14:22 UTC, merged