Feat/api blob proofs
celenium-io/celestia-indexer pull request #312
Opened 2024-11-29 14:21 UTC by k-karuna

2024-11-30 11:14 UTC, aopoltorzhicky requested changes

2024-11-30 11:14 UTC, aopoltorzhicky commented on cmd/api/handler/responses/ods.go
> +	ShareVersionZero = uint8(0)
https://github.com/celestiaorg/go-square/blob/206b9278e7ca983b6cb58fe2c6e2953ee23053e8/share/consts.go#L21

можешь импортировать эти константы из кора

2024-11-30 11:14 UTC, aopoltorzhicky commented on cmd/api/handler/responses/ods.go
> +		if !bytes.Contains(SupportedShareVersions, []byte{s.Version()}) {
Для простоты понимания можно написать просто `s.Version() <= 1`, потому что только 2 версии доступно пока

2024-11-30 11:14 UTC, aopoltorzhicky commented on cmd/api/handler/responses/ods.go
> +			}
Этот коммент для нас неактуален.  У нас проверка выше происходит сейчас

2024-11-30 11:14 UTC, aopoltorzhicky commented on cmd/api/handler/responses/ods.go
> +			if i == (len(sequences))-1 { // last sequence element
Вот этого условия не понял. Зачем оно здесь?

2024-11-30 11:14 UTC, aopoltorzhicky commented on pkg/node/rpc/blob.go
> +package rpc
Не забудь header с лицензиями добавить потом

2024-11-30 11:14 UTC, aopoltorzhicky commented on pkg/node/rpc/blob.go
> +	if level != 0 {
По идее все параметры запроса у тебя обязательные, поэтому можешь кидать ошибку, если хоть кто-то из них меньше 0, а level должен быть больше 0

2024-12-02 14:08 UTC, k-karuna commented on cmd/api/handler/responses/ods.go
> +			if i == (len(sequences))-1 { // last sequence element
Потому что я возвращаю индексы первого и последнего элемента шары, причем индекс последнего берется из следующей sequence

(второй возвращаемый параметр) `return nsStartIdx + seq.startShareIndex, nsStartIdx + sequences[i+1].startShareIndex - 1, err`

Поэтому нужна проверка, чтобы не вылезти за пределы sequences

2024-12-03 09:21 UTC, aopoltorzhicky requested changes

2024-12-03 09:21 UTC, aopoltorzhicky commented on cmd/api/handler/namespace.go
> +	proofs, err := handler.node.BlobProofs(c.Request().Context(), req.Height, startBlobIdx, endBlobIdx)
Здесь может быть startBlobIdx == endBlobIdx == 0. По крайней мере у меня так получилось с первым попавшимся блобом. Из-=за этого нода пятистоит

2024-12-05 09:55 UTC, aopoltorzhicky requested changes

2024-12-05 09:55 UTC, aopoltorzhicky commented on pkg/node/api.go
> +	BlobProofs(ctx context.Context, level pkgTypes.Level, startShare, endShare int) (pkgTypes.BlobProof, error)
По идее, это можно выпилить

2024-12-05 13:33 UTC, merged